### ISSUE TITLE
Unchanged svg

### ISSUE THREAD

**Issue by Loremly** [NYRI4/Discolored#12]
The svg that shows when it tells you to invite people to a server is still uncolored. 
![image](https://user-images.githubusercontent.com/86319836/131196771-453f1f94-5e4c-4315-94d5-25ac346e627b.png)

**Comment by NYRI4** [comment]
Can you pls give me the two (light/dark) new URLs, I can't get those one

**Comment by NYRI4** [comment]
## Unchanged SVGs

Here's the list of unchanged SVGs to test (because I can't do it myself), I tried all the other ones and changed the ones Discord updated.

| Status | SVG | Comment |
| :-: | :-: | :-: |
| ❌ | <img width=100 src="https://nyri4.github.io/Discolored/assets/boost.svg"/> | Same emplacement as thread notifications, under the server name |
| ❌ | <img width=100 src="https://nyri4.github.io/Discolored/assets/key.svg"/> | Like boost emplacement, append when you don't have 2FA enabled |
| ❌ | <img width=100 src="https://nyri4.github.io/Discolored/assets/switch.svg"/> | Like boost emplacement, I don't remember what's for |
| ❌ | <img width=100 src="https://nyri4.github.io/Discolored/assets/crash.svg"/> | Well when a crash appears |
| ❌ | <img width=100 src="https://nyri4.github.io/Discolored/assets/groups.svg"/> | I never saw where it was but here's the class if it can help : <br>`.noFriends-1fVUuM .errorStateIcon-3fNXE5` |
| ❌ | <img width=100 src="https://nyri4.github.io/Discolored/assets/server_outage.svg"/> | Pretty rare to find, when randomly a server don't work |
| ❌ | <img width=100 src="https://nyri4.github.io/Discolored/assets/phones.svg"/> | Never saw that one |
| ❌ | <img width=100 src="https://nyri4.github.io/Discolored/assets/unclaimed.svg"/> | Never saw that one |

**Comment by Loremly** [comment]
So sorry about not seeings this, but i did find another channel notice that isnt colored

`.channelNotice-I0gkZS` 
`background-image: url(/assets/0a14344c0e0bfe3a52aa245ecaaebca7.svg)` 
Url is the same for both light and dark mode.
![image](https://user-images.githubusercontent.com/86319836/144944507-017da634-e2a0-4fcc-84f4-32a001b4c504.png)
